name: Lint Commit
on: pull_request

permissions:
  contents: read
  pull-requests: read

jobs:
  conventional:
    name: Conventional Commit Linter
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - uses: taskmedia/action-conventional-commits@v1.1.13
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          types: "fix|feat|revert|ci|docs|chore"